[build]
  publish = "public"
  command = "yarn build"

[[redirects]]
  from = "/webar/*"
  to = "https://atsuhan-webar.netlify.app/:splat"
  status = 200
  force = true

[build.environment]
  YARN_VERSION = "1.22.0"
  NODE_VERSION = "13.5.0"
  YARN_FLAGS = "--no-ignore-optional"
  NODE_OPTIONS = "--max_old_space_size=4096"